//////DECLARER LES VARIABLES CONCERNEES ICI ; CREER UN SCRIPT PAREIL POUR CHAQUE OBJET

toto=ini_param[0]//CET OJET A BESOIN DES VARIABLES TOTO...
tata=ini_param[1] //CET OJET A BESOIN DES VARIABLES TATA...
titi=ini_param[2] //CET OJET A BESOIN DES VARIABLES TITI...



ini_param_name[0]="toto"//VOICI COMENT ON LES NOMME...
ini_param_name[1]="tata"//
ini_param_name[2]="titi"//